# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.7.2"

package:
  name: python-librt
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/librt/librt-${{ version }}.tar.gz
    sha256: 48aa0f311bdf90ec9a63e3669b6aff04967f24f2f67fe9372c570a21dc9ae873

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python

tests:
  - python:
      imports: librt
      pip_check: true
  - files:
      source: smoke_tests.py
    requirements:
      run:
        - mypy_extensions
        - pytest
    script:
      - pytest -vv --tb=long --color=yes smoke_tests.py

about:
  homepage: https://pypi.org/project/librt
  repository: https://github.com/mypyc/librt
  summary: Mypyc runtime library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/mypy
